version: "2"

services:
    mysql:
      image: mysql:5.7
      environment:
          - MYSQL_ROOT_PASSWORD=labsecret
          - MYSQL_USER=lab
          - MYSQL_PASSWORD=lab123
          - MYSQL_DATABASE=note
      ports:
          - 127.0.0.1:3307:3306
      networks:
          - back-tier
      hostname: mysql
      cpu_shares: 512
      mem_limit: 1073741824
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - mysql:db
      ports:
          - 81:80
      networks:
          - back-tier
      hostname: phpmyadmin
      cpu_shares: 512
      mem_limit: 536870912

networks:
    # front-tier:
    back-tier:
